name: Update repository

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/repo.json"
      - "**/packages/**.json"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7

      - name: Install Python dependencies
        run: python3 -m pip install requests

      - name: Update hashes
        run: |
          python3 .github/workflows/scripts/hash.py

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.NITROPKG_PRIVATE_KEY }}
          passphrase: ${{ secrets.NITROPKG_PRIVATE_KEY_PASSPHRASE }}
          trust_level: 5

      - name: Sign repositories
        run: |
          set -e
          find . -type f -name "repo.json" -not -path "*/.git/*" | while read -r file; do
            gpg --batch --yes --armor --detach-sign --output "${file}.asc" "$file"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -- "*.json" "*.asc"
          if ! git diff --staged --quiet; then
            git commit -m "Update repositories"
            git push
          else
            echo "No changes were made."
          fi
