name: Update repository

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/repo.json"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sign:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.NITROPKG_PRIVATE_KEY }}
          passphrase: ${{ secrets.NITROPKG_PRIVATE_KEY_PASSPHRASE }}
          trust_level: 5

      - name: Sign repo.json files
        run: |
          set -e
          find . -type f -name "repo.json" -not -path "*/.git/*" | while read -r file; do
            gpg --batch --yes --armor --detach-sign --output "${file}.asc" "$file"
          done

      # Runs a set of commands using the runners shell
      - name: Commit and push signatures
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -- "*.asc"
          if ! git diff --staged --quiet; then
            git commit -m "Update signatures"
            git push
          else
            echo "No changes were made."
          fi
